{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d65e2651-066a-4676-a5ff-754277d42457",
   "metadata": {},
   "outputs": [],
   "source": [
    "project:\n",
    "  type: website\n",
    "  output-dir: _site\n",
    "\n",
    "# The 'site' key holds metadata for the whole site\n",
    "site:\n",
    "  title: \"Your Name\"\n",
    "  description: \"A blog and portfolio about data science, quantitative analysis, and more.\"\n",
    "  site-url: \"https://your-github-username.github.io\" # IMPORTANT: Add your final website URL here\n",
    "  twitter-card: true # Enable Twitter card previews\n",
    "  open-graph: true   # Enable previews for Facebook, LinkedIn, etc.\n",
    "  \n",
    "website:\n",
    "  title: \"Your Name\" # This title appears in the navbar\n",
    "\n",
    "  # --- Navigation Bar ---\n",
    "  navbar:\n",
    "    logo: assets/logo.png # Optional: Add a small logo image\n",
    "    left:\n",
    "      - href: index.qmd\n",
    "        text: Home\n",
    "      - href: blog/index.qmd\n",
    "        text: Blog\n",
    "      - href: projects/index.qmd\n",
    "        text: Projects\n",
    "      - href: about.qmd\n",
    "        text: About\n",
    "      - href: cv.qmd\n",
    "        text: CV\n",
    "    right:\n",
    "      - icon: github\n",
    "        href: https://github.com/your-github-username\n",
    "      - icon: linkedin\n",
    "        href: https://linkedin.com/in/your-linkedin\n",
    "  \n",
    "  # --- Footer ---\n",
    "  page-footer:\n",
    "    left: \"© 2025, Your Name. Built with Quarto.\"\n",
    "    right:\n",
    "      - icon: github\n",
    "        href: https://github.com/your-github-username\n",
    "\n",
    "  # --- Enable Site Search ---\n",
    "  search: true\n",
    "  \n",
    "  # --- Enable Comments with Giscus (a popular choice) ---\n",
    "  comments:\n",
    "    giscus:\n",
    "      repo: your-github-username/your-repo-name # IMPORTANT: Change this\n",
    "      \n",
    "format:\n",
    "  html:\n",
    "    theme: cosmo\n",
    "    css: styles.css\n",
    "    toc: true"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
